update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,7 +10,25 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
-    - name: Test script
-      timeout-minutes: 1
-      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
-      run: ./ghaction_script.sh
+    - name: Run a one-line script
+      run: |
+        exit_script() {
+            echo "Received signal: $1"
+            echo "Going to kill a process"
+            trap - $1 # clear the trap
+            # Do stuff to clean up
+            # ex: Kill -2 1234
+            echo "Sending"
+        }
+        trap 'exit_script SIGHUP' SIGHUP
+        trap 'exit_script SIGINT' SIGINT
+        trap 'exit_script SIGTERM' SIGTERM
+
+        echo "running the job! PID: $$"
+        while true; do sleep 1; echo "waiting..."; done
+        echo "Done"
+
+    # - name: Test script
+    #   timeout-minutes: 1
+    #   shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
+    #   run: ./ghaction_script.sh
